# ----------------------------------------------------------------------------------------------------------------------

# Container.

dist: trusty
sudo: required
language: generic
script: ./.travis.bash

# ----------------------------------------------------------------------------------------------------------------------

# Notifications.

notifications:
  email: false # Disable.
  slack: websharks:EpVKoMF6MQKjLKVw0CAX33Og

# ----------------------------------------------------------------------------------------------------------------------

# <custom> Begin custom matrix.

matrix: # Tests for Comet Cache WordPress plugin.

  include: # Cover both ends of our PHP spectrum.

    - env: CI_RUN=PHP_VERSION=7.0,WP=standard,WP_VERSION=latest
    - env: CI_RUN=PHP_VERSION=7.0,WP=multisite,WP_VERSION=latest

  fast_finish: true # Before allowed failures.

# </custom>
